### ISSUE TITLE
Card is not displayed

### ISSUE THREAD

**Issue by kobi80** [wichers/lovelace-comfoair#3]
Unfortunately I can't see the Card.

I entered the following

```
type: custom:comfoair-card
entity: climate.ca350_climate
```
![image](https://user-images.githubusercontent.com/79660810/226907510-1375c129-2d56-4a28-a8cf-8494899b8055.png)

**Comment by ptrkp** [comment]
I have the same issue.
Any help is welcome.

**Comment by matejek** [comment]
same here

**Comment by adch17490** [comment]
I had the same problem. And I solved it checking entity names one by one. All sensor.<name> and binary_input.<name> defined in HA should be the same as the names defined in the comfoair-card.js
You can check the differences if you look for the errors of .js in your browser.
When everything is ok, you'll see the picture in background at least.

Example:
<div>${this.hass.states['**sensor.comfoair_comfoair_outside_air_temperature**'].state}°C</div>

**Comment by wichers** [comment]
Variables need to be matched to the comfoaue addon. This has been fixed in latest version.
